export const FETCH_DATA_SUCCESS = 'FETCH_DATA_SUCCESS';
export const FETCH_DATA_FAILURE = 'FETCH_DATA_FAILURE';
export const FETCH_CAT_DATA_SUCCESS = 'FETCH_CAT_DATA_SUCCESS';
export const FETCH_CAT_DATA_FAILURE = 'FETCH_CAT_DATA_FAILURE';
export const FETCH_COURSE_DATA_SUCCESS = 'FETCH_COURSE_DATA_SUCCESS';
export const FETCH_COURSE_DATA_FAILURE = 'FETCH_COURSE_DATA_FAILURE';
export const FETCH_DATA_REQUEST = 'FETCH_DATA_REQUEST';

export const fetchDataRequest = () => ({
    type: FETCH_DATA_REQUEST,
});